name = "asu-auth"
main = "src/index.ts"
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[limits]
cpu_ms = 100

[[routes]]
pattern = "auth.xn--as-yka.app"
custom_domain = true

[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "asu-auth"
database_id = "1500d65b-9e81-4006-bd77-c71d3555e263"
