/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthedOrganisationenRouteImport } from './routes/_authed/organisationen'
import { Route as AppPersonalRouteImport } from './routes/_app/personal'
import { Route as AppEinstellungenRouteImport } from './routes/_app/einstellungen'
import { Route as AuthedEinladungCodeRouteImport } from './routes/_authed/einladung/$code'
import { Route as AppEinsatzOperationSlugIndexRouteImport } from './routes/_app/einsatz/$operationSlug/index'
import { Route as AppEinsatzOperationSlugTruppsRouteImport } from './routes/_app/einsatz/$operationSlug/trupps'
import { Route as AppEinsatzOperationSlugExportRouteImport } from './routes/_app/einsatz/$operationSlug/export'

const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthedOrganisationenRoute = AuthedOrganisationenRouteImport.update({
  id: '/organisationen',
  path: '/organisationen',
  getParentRoute: () => AuthedRoute,
} as any)
const AppPersonalRoute = AppPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppRoute,
} as any)
const AppEinstellungenRoute = AppEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AppRoute,
} as any)
const AuthedEinladungCodeRoute = AuthedEinladungCodeRouteImport.update({
  id: '/einladung/$code',
  path: '/einladung/$code',
  getParentRoute: () => AuthedRoute,
} as any)
const AppEinsatzOperationSlugIndexRoute =
  AppEinsatzOperationSlugIndexRouteImport.update({
    id: '/einsatz/$operationSlug/',
    path: '/einsatz/$operationSlug/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEinsatzOperationSlugTruppsRoute =
  AppEinsatzOperationSlugTruppsRouteImport.update({
    id: '/einsatz/$operationSlug/trupps',
    path: '/einsatz/$operationSlug/trupps',
    getParentRoute: () => AppRoute,
  } as any)
const AppEinsatzOperationSlugExportRoute =
  AppEinsatzOperationSlugExportRouteImport.update({
    id: '/einsatz/$operationSlug/export',
    path: '/einsatz/$operationSlug/export',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/registrieren': typeof RegistrierenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/personal': typeof AppPersonalRoute
  '/organisationen': typeof AuthedOrganisationenRoute
  '/einladung/$code': typeof AuthedEinladungCodeRoute
  '/einsatz/$operationSlug/export': typeof AppEinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof AppEinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug/': typeof AppEinsatzOperationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/registrieren': typeof RegistrierenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/personal': typeof AppPersonalRoute
  '/organisationen': typeof AuthedOrganisationenRoute
  '/einladung/$code': typeof AuthedEinladungCodeRoute
  '/einsatz/$operationSlug/export': typeof AppEinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof AppEinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug': typeof AppEinsatzOperationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/registrieren': typeof RegistrierenRoute
  '/_app/einstellungen': typeof AppEinstellungenRoute
  '/_app/personal': typeof AppPersonalRoute
  '/_authed/organisationen': typeof AuthedOrganisationenRoute
  '/_app/': typeof AppIndexRoute
  '/_authed/einladung/$code': typeof AuthedEinladungCodeRoute
  '/_app/einsatz/$operationSlug/export': typeof AppEinsatzOperationSlugExportRoute
  '/_app/einsatz/$operationSlug/trupps': typeof AppEinsatzOperationSlugTruppsRoute
  '/_app/einsatz/$operationSlug/': typeof AppEinsatzOperationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/registrieren'
    | '/einstellungen'
    | '/personal'
    | '/organisationen'
    | '/einladung/$code'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/registrieren'
    | '/einstellungen'
    | '/personal'
    | '/organisationen'
    | '/einladung/$code'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_authed'
    | '/anmelden'
    | '/registrieren'
    | '/_app/einstellungen'
    | '/_app/personal'
    | '/_authed/organisationen'
    | '/_app/'
    | '/_authed/einladung/$code'
    | '/_app/einsatz/$operationSlug/export'
    | '/_app/einsatz/$operationSlug/trupps'
    | '/_app/einsatz/$operationSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  RegistrierenRoute: typeof RegistrierenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authed/organisationen': {
      id: '/_authed/organisationen'
      path: '/organisationen'
      fullPath: '/organisationen'
      preLoaderRoute: typeof AuthedOrganisationenRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_app/personal': {
      id: '/_app/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AppPersonalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einstellungen': {
      id: '/_app/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AppEinstellungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authed/einladung/$code': {
      id: '/_authed/einladung/$code'
      path: '/einladung/$code'
      fullPath: '/einladung/$code'
      preLoaderRoute: typeof AuthedEinladungCodeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_app/einsatz/$operationSlug/': {
      id: '/_app/einsatz/$operationSlug/'
      path: '/einsatz/$operationSlug'
      fullPath: '/einsatz/$operationSlug/'
      preLoaderRoute: typeof AppEinsatzOperationSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einsatz/$operationSlug/trupps': {
      id: '/_app/einsatz/$operationSlug/trupps'
      path: '/einsatz/$operationSlug/trupps'
      fullPath: '/einsatz/$operationSlug/trupps'
      preLoaderRoute: typeof AppEinsatzOperationSlugTruppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einsatz/$operationSlug/export': {
      id: '/_app/einsatz/$operationSlug/export'
      path: '/einsatz/$operationSlug/export'
      fullPath: '/einsatz/$operationSlug/export'
      preLoaderRoute: typeof AppEinsatzOperationSlugExportRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

declare module './routes/_app' {
  const createFileRoute: CreateFileRoute<
    '/_app',
    FileRoutesByPath['/_app']['parentRoute'],
    FileRoutesByPath['/_app']['id'],
    FileRoutesByPath['/_app']['path'],
    FileRoutesByPath['/_app']['fullPath']
  >
}
declare module './routes/_authed' {
  const createFileRoute: CreateFileRoute<
    '/_authed',
    FileRoutesByPath['/_authed']['parentRoute'],
    FileRoutesByPath['/_authed']['id'],
    FileRoutesByPath['/_authed']['path'],
    FileRoutesByPath['/_authed']['fullPath']
  >
}
declare module './routes/anmelden' {
  const createFileRoute: CreateFileRoute<
    '/anmelden',
    FileRoutesByPath['/anmelden']['parentRoute'],
    FileRoutesByPath['/anmelden']['id'],
    FileRoutesByPath['/anmelden']['path'],
    FileRoutesByPath['/anmelden']['fullPath']
  >
}
declare module './routes/registrieren' {
  const createFileRoute: CreateFileRoute<
    '/registrieren',
    FileRoutesByPath['/registrieren']['parentRoute'],
    FileRoutesByPath['/registrieren']['id'],
    FileRoutesByPath['/registrieren']['path'],
    FileRoutesByPath['/registrieren']['fullPath']
  >
}
declare module './routes/_app/einstellungen' {
  const createFileRoute: CreateFileRoute<
    '/_app/einstellungen',
    FileRoutesByPath['/_app/einstellungen']['parentRoute'],
    FileRoutesByPath['/_app/einstellungen']['id'],
    FileRoutesByPath['/_app/einstellungen']['path'],
    FileRoutesByPath['/_app/einstellungen']['fullPath']
  >
}
declare module './routes/_app/personal' {
  const createFileRoute: CreateFileRoute<
    '/_app/personal',
    FileRoutesByPath['/_app/personal']['parentRoute'],
    FileRoutesByPath['/_app/personal']['id'],
    FileRoutesByPath['/_app/personal']['path'],
    FileRoutesByPath['/_app/personal']['fullPath']
  >
}
declare module './routes/_authed/organisationen' {
  const createFileRoute: CreateFileRoute<
    '/_authed/organisationen',
    FileRoutesByPath['/_authed/organisationen']['parentRoute'],
    FileRoutesByPath['/_authed/organisationen']['id'],
    FileRoutesByPath['/_authed/organisationen']['path'],
    FileRoutesByPath['/_authed/organisationen']['fullPath']
  >
}
declare module './routes/_app/index' {
  const createFileRoute: CreateFileRoute<
    '/_app/',
    FileRoutesByPath['/_app/']['parentRoute'],
    FileRoutesByPath['/_app/']['id'],
    FileRoutesByPath['/_app/']['path'],
    FileRoutesByPath['/_app/']['fullPath']
  >
}
declare module './routes/_authed/einladung/$code' {
  const createFileRoute: CreateFileRoute<
    '/_authed/einladung/$code',
    FileRoutesByPath['/_authed/einladung/$code']['parentRoute'],
    FileRoutesByPath['/_authed/einladung/$code']['id'],
    FileRoutesByPath['/_authed/einladung/$code']['path'],
    FileRoutesByPath['/_authed/einladung/$code']['fullPath']
  >
}
declare module './routes/_app/einsatz/$operationSlug/export' {
  const createFileRoute: CreateFileRoute<
    '/_app/einsatz/$operationSlug/export',
    FileRoutesByPath['/_app/einsatz/$operationSlug/export']['parentRoute'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/export']['id'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/export']['path'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/export']['fullPath']
  >
}
declare module './routes/_app/einsatz/$operationSlug/trupps' {
  const createFileRoute: CreateFileRoute<
    '/_app/einsatz/$operationSlug/trupps',
    FileRoutesByPath['/_app/einsatz/$operationSlug/trupps']['parentRoute'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/trupps']['id'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/trupps']['path'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/trupps']['fullPath']
  >
}
declare module './routes/_app/einsatz/$operationSlug/index' {
  const createFileRoute: CreateFileRoute<
    '/_app/einsatz/$operationSlug/',
    FileRoutesByPath['/_app/einsatz/$operationSlug/']['parentRoute'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/']['id'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/']['path'],
    FileRoutesByPath['/_app/einsatz/$operationSlug/']['fullPath']
  >
}

interface AppRouteChildren {
  AppEinstellungenRoute: typeof AppEinstellungenRoute
  AppPersonalRoute: typeof AppPersonalRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEinsatzOperationSlugExportRoute: typeof AppEinsatzOperationSlugExportRoute
  AppEinsatzOperationSlugTruppsRoute: typeof AppEinsatzOperationSlugTruppsRoute
  AppEinsatzOperationSlugIndexRoute: typeof AppEinsatzOperationSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEinstellungenRoute: AppEinstellungenRoute,
  AppPersonalRoute: AppPersonalRoute,
  AppIndexRoute: AppIndexRoute,
  AppEinsatzOperationSlugExportRoute: AppEinsatzOperationSlugExportRoute,
  AppEinsatzOperationSlugTruppsRoute: AppEinsatzOperationSlugTruppsRoute,
  AppEinsatzOperationSlugIndexRoute: AppEinsatzOperationSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthedRouteChildren {
  AuthedOrganisationenRoute: typeof AuthedOrganisationenRoute
  AuthedEinladungCodeRoute: typeof AuthedEinladungCodeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrganisationenRoute: AuthedOrganisationenRoute,
  AuthedEinladungCodeRoute: AuthedEinladungCodeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  RegistrierenRoute: RegistrierenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
