/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as OrganisationenRouteImport } from './routes/organisationen'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EinladungCodeRouteImport } from './routes/einladung/$code'
import { Route as EinsatzOperationSlugIndexRouteImport } from './routes/einsatz/$operationSlug/index'
import { Route as EinsatzOperationSlugTruppsRouteImport } from './routes/einsatz/$operationSlug/trupps'
import { Route as EinsatzOperationSlugExportRouteImport } from './routes/einsatz/$operationSlug/export'

const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationenRoute = OrganisationenRouteImport.update({
  id: '/organisationen',
  path: '/organisationen',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EinladungCodeRoute = EinladungCodeRouteImport.update({
  id: '/einladung/$code',
  path: '/einladung/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsatzOperationSlugIndexRoute =
  EinsatzOperationSlugIndexRouteImport.update({
    id: '/einsatz/$operationSlug/',
    path: '/einsatz/$operationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EinsatzOperationSlugTruppsRoute =
  EinsatzOperationSlugTruppsRouteImport.update({
    id: '/einsatz/$operationSlug/trupps',
    path: '/einsatz/$operationSlug/trupps',
    getParentRoute: () => rootRouteImport,
  } as any)
const EinsatzOperationSlugExportRoute =
  EinsatzOperationSlugExportRouteImport.update({
    id: '/einsatz/$operationSlug/export',
    path: '/einsatz/$operationSlug/export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/organisationen': typeof OrganisationenRoute
  '/personal': typeof PersonalRoute
  '/registrieren': typeof RegistrierenRoute
  '/einladung/$code': typeof EinladungCodeRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug/': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/organisationen': typeof OrganisationenRoute
  '/personal': typeof PersonalRoute
  '/registrieren': typeof RegistrierenRoute
  '/einladung/$code': typeof EinladungCodeRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/organisationen': typeof OrganisationenRoute
  '/personal': typeof PersonalRoute
  '/registrieren': typeof RegistrierenRoute
  '/einladung/$code': typeof EinladungCodeRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug/': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/einstellungen'
    | '/organisationen'
    | '/personal'
    | '/registrieren'
    | '/einladung/$code'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/einstellungen'
    | '/organisationen'
    | '/personal'
    | '/registrieren'
    | '/einladung/$code'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug'
  id:
    | '__root__'
    | '/'
    | '/anmelden'
    | '/einstellungen'
    | '/organisationen'
    | '/personal'
    | '/registrieren'
    | '/einladung/$code'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnmeldenRoute: typeof AnmeldenRoute
  EinstellungenRoute: typeof EinstellungenRoute
  OrganisationenRoute: typeof OrganisationenRoute
  PersonalRoute: typeof PersonalRoute
  RegistrierenRoute: typeof RegistrierenRoute
  EinladungCodeRoute: typeof EinladungCodeRoute
  EinsatzOperationSlugExportRoute: typeof EinsatzOperationSlugExportRoute
  EinsatzOperationSlugTruppsRoute: typeof EinsatzOperationSlugTruppsRoute
  EinsatzOperationSlugIndexRoute: typeof EinsatzOperationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisationen': {
      id: '/organisationen'
      path: '/organisationen'
      fullPath: '/organisationen'
      preLoaderRoute: typeof OrganisationenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einladung/$code': {
      id: '/einladung/$code'
      path: '/einladung/$code'
      fullPath: '/einladung/$code'
      preLoaderRoute: typeof EinladungCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/': {
      id: '/einsatz/$operationSlug/'
      path: '/einsatz/$operationSlug'
      fullPath: '/einsatz/$operationSlug/'
      preLoaderRoute: typeof EinsatzOperationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/trupps': {
      id: '/einsatz/$operationSlug/trupps'
      path: '/einsatz/$operationSlug/trupps'
      fullPath: '/einsatz/$operationSlug/trupps'
      preLoaderRoute: typeof EinsatzOperationSlugTruppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/export': {
      id: '/einsatz/$operationSlug/export'
      path: '/einsatz/$operationSlug/export'
      fullPath: '/einsatz/$operationSlug/export'
      preLoaderRoute: typeof EinsatzOperationSlugExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/anmelden' {
  const createFileRoute: CreateFileRoute<
    '/anmelden',
    FileRoutesByPath['/anmelden']['parentRoute'],
    FileRoutesByPath['/anmelden']['id'],
    FileRoutesByPath['/anmelden']['path'],
    FileRoutesByPath['/anmelden']['fullPath']
  >
}
declare module './routes/einstellungen' {
  const createFileRoute: CreateFileRoute<
    '/einstellungen',
    FileRoutesByPath['/einstellungen']['parentRoute'],
    FileRoutesByPath['/einstellungen']['id'],
    FileRoutesByPath['/einstellungen']['path'],
    FileRoutesByPath['/einstellungen']['fullPath']
  >
}
declare module './routes/organisationen' {
  const createFileRoute: CreateFileRoute<
    '/organisationen',
    FileRoutesByPath['/organisationen']['parentRoute'],
    FileRoutesByPath['/organisationen']['id'],
    FileRoutesByPath['/organisationen']['path'],
    FileRoutesByPath['/organisationen']['fullPath']
  >
}
declare module './routes/personal' {
  const createFileRoute: CreateFileRoute<
    '/personal',
    FileRoutesByPath['/personal']['parentRoute'],
    FileRoutesByPath['/personal']['id'],
    FileRoutesByPath['/personal']['path'],
    FileRoutesByPath['/personal']['fullPath']
  >
}
declare module './routes/registrieren' {
  const createFileRoute: CreateFileRoute<
    '/registrieren',
    FileRoutesByPath['/registrieren']['parentRoute'],
    FileRoutesByPath['/registrieren']['id'],
    FileRoutesByPath['/registrieren']['path'],
    FileRoutesByPath['/registrieren']['fullPath']
  >
}
declare module './routes/einladung/$code' {
  const createFileRoute: CreateFileRoute<
    '/einladung/$code',
    FileRoutesByPath['/einladung/$code']['parentRoute'],
    FileRoutesByPath['/einladung/$code']['id'],
    FileRoutesByPath['/einladung/$code']['path'],
    FileRoutesByPath['/einladung/$code']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/export' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/export',
    FileRoutesByPath['/einsatz/$operationSlug/export']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/trupps' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/trupps',
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/index' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/',
    FileRoutesByPath['/einsatz/$operationSlug/']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnmeldenRoute: AnmeldenRoute,
  EinstellungenRoute: EinstellungenRoute,
  OrganisationenRoute: OrganisationenRoute,
  PersonalRoute: PersonalRoute,
  RegistrierenRoute: RegistrierenRoute,
  EinladungCodeRoute: EinladungCodeRoute,
  EinsatzOperationSlugExportRoute: EinsatzOperationSlugExportRoute,
  EinsatzOperationSlugTruppsRoute: EinsatzOperationSlugTruppsRoute,
  EinsatzOperationSlugIndexRoute: EinsatzOperationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
