/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EinsatzOperationSlugRouteImport } from './routes/einsatz/$operationSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsatzOperationSlugRoute = EinsatzOperationSlugRouteImport.update({
  id: '/einsatz/$operationSlug',
  path: '/einsatz/$operationSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/einsatz/$operationSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/einsatz/$operationSlug'
  id: '__root__' | '/' | '/einsatz/$operationSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinsatzOperationSlugRoute: typeof EinsatzOperationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug': {
      id: '/einsatz/$operationSlug'
      path: '/einsatz/$operationSlug'
      fullPath: '/einsatz/$operationSlug'
      preLoaderRoute: typeof EinsatzOperationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug',
    FileRoutesByPath['/einsatz/$operationSlug']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug']['id'],
    FileRoutesByPath['/einsatz/$operationSlug']['path'],
    FileRoutesByPath['/einsatz/$operationSlug']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinsatzOperationSlugRoute: EinsatzOperationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
