/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EinsatzOperationSlugIndexRouteImport } from './routes/einsatz/$operationSlug/index'
import { Route as EinsatzOperationSlugTruppsRouteImport } from './routes/einsatz/$operationSlug/trupps'
import { Route as EinsatzOperationSlugExportRouteImport } from './routes/einsatz/$operationSlug/export'

const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsatzOperationSlugIndexRoute =
  EinsatzOperationSlugIndexRouteImport.update({
    id: '/einsatz/$operationSlug/',
    path: '/einsatz/$operationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EinsatzOperationSlugTruppsRoute =
  EinsatzOperationSlugTruppsRouteImport.update({
    id: '/einsatz/$operationSlug/trupps',
    path: '/einsatz/$operationSlug/trupps',
    getParentRoute: () => rootRouteImport,
  } as any)
const EinsatzOperationSlugExportRoute =
  EinsatzOperationSlugExportRouteImport.update({
    id: '/einsatz/$operationSlug/export',
    path: '/einsatz/$operationSlug/export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/einsatz/$operationSlug/export': typeof EinsatzOperationSlugExportRoute
  '/einsatz/$operationSlug/trupps': typeof EinsatzOperationSlugTruppsRoute
  '/einsatz/$operationSlug/': typeof EinsatzOperationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/einsatz/$operationSlug/export'
    | '/einsatz/$operationSlug/trupps'
    | '/einsatz/$operationSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  EinsatzOperationSlugExportRoute: typeof EinsatzOperationSlugExportRoute
  EinsatzOperationSlugTruppsRoute: typeof EinsatzOperationSlugTruppsRoute
  EinsatzOperationSlugIndexRoute: typeof EinsatzOperationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/export': {
      id: '/einsatz/$operationSlug/export'
      path: '/einsatz/$operationSlug/export'
      fullPath: '/einsatz/$operationSlug/export'
      preLoaderRoute: typeof EinsatzOperationSlugExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/trupps': {
      id: '/einsatz/$operationSlug/trupps'
      path: '/einsatz/$operationSlug/trupps'
      fullPath: '/einsatz/$operationSlug/trupps'
      preLoaderRoute: typeof EinsatzOperationSlugTruppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatz/$operationSlug/': {
      id: '/einsatz/$operationSlug/'
      path: '/einsatz/$operationSlug'
      fullPath: '/einsatz/$operationSlug'
      preLoaderRoute: typeof EinsatzOperationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/einstellungen' {
  const createFileRoute: CreateFileRoute<
    '/einstellungen',
    FileRoutesByPath['/einstellungen']['parentRoute'],
    FileRoutesByPath['/einstellungen']['id'],
    FileRoutesByPath['/einstellungen']['path'],
    FileRoutesByPath['/einstellungen']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/export' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/export',
    FileRoutesByPath['/einsatz/$operationSlug/export']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/export']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/trupps' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/trupps',
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/trupps']['fullPath']
  >
}
declare module './routes/einsatz/$operationSlug/index' {
  const createFileRoute: CreateFileRoute<
    '/einsatz/$operationSlug/',
    FileRoutesByPath['/einsatz/$operationSlug/']['parentRoute'],
    FileRoutesByPath['/einsatz/$operationSlug/']['id'],
    FileRoutesByPath['/einsatz/$operationSlug/']['path'],
    FileRoutesByPath['/einsatz/$operationSlug/']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  EinsatzOperationSlugExportRoute: EinsatzOperationSlugExportRoute,
  EinsatzOperationSlugTruppsRoute: EinsatzOperationSlugTruppsRoute,
  EinsatzOperationSlugIndexRoute: EinsatzOperationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
